/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WordProblemGeneratorISU;

// imports required for this assignment
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 * Muntaqa Mahmood
 * January 07, 2020
 */
public class WordProblemGeneratorISU extends javax.swing.JFrame {
    // 
    String[][] Qs = new String [6][2];
    String Rec;
    String Equation;
    /**
     * Creates new form NewJFrame
     */
    public WordProblemGeneratorISU() {
        initComponents();
        findxtangent.setEnabled(false);
        findytangent.setEnabled(false);
        derbutton.setEnabled(false);
        secbutton.setEnabled(false);
        recbutton.setEnabled(false);
        tanbutton.setEnabled(false);
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        SlopeOfTangent = new javax.swing.JButton();
        SlopeOfSecant = new javax.swing.JButton();
        RecurringNumbers = new javax.swing.JButton();
        Derivative = new javax.swing.JButton();
        Title1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InputX1Secant = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InputX2Secant = new javax.swing.JTextField();
        Title2 = new javax.swing.JLabel();
        InputEquationSecant = new javax.swing.JTextField();
        findxtangent = new javax.swing.JButton();
        findytangent = new javax.swing.JButton();
        Title4 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        InputXTangent = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        InputYTangent = new javax.swing.JTextField();
        Title5 = new javax.swing.JLabel();
        InputEquationTangent = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        InputEquationDerivative = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MainOutput = new javax.swing.JTextArea();
        Titlenumber = new javax.swing.JLabel();
        InputRecurring = new javax.swing.JTextField();
        recbutton = new javax.swing.JButton();
        derbutton = new javax.swing.JButton();
        tanbutton = new javax.swing.JButton();
        secbutton = new javax.swing.JButton();
        helpbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        Title.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        Title.setText("Word Problem Generator");

        SlopeOfTangent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SlopeOfTangent.setText("Equation of Tangent");
        SlopeOfTangent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlopeOfTangentActionPerformed(evt);
            }
        });

        SlopeOfSecant.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SlopeOfSecant.setText("Slope of Secant");
        SlopeOfSecant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlopeOfSecantActionPerformed(evt);
            }
        });

        RecurringNumbers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RecurringNumbers.setText("Recurring Numbers");
        RecurringNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecurringNumbersActionPerformed(evt);
            }
        });

        Derivative.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Derivative.setText("Derivative");
        Derivative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DerivativeActionPerformed(evt);
            }
        });

        Title1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Title1.setText("Input Coordinate :");

        jLabel2.setText("X₁=");

        jLabel3.setText("X₂=");

        Title2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Title2.setText("Input Equation Of Graph :");

        findxtangent.setText("Find X");
        findxtangent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findxtangentActionPerformed(evt);
            }
        });

        findytangent.setText("Find Y");
        findytangent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findytangentActionPerformed(evt);
            }
        });

        Title4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Title4.setText("Input Coordinate :");

        ExitButton.setText("Exit Program");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("X=");

        jLabel7.setText("Y=");

        Title5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Title5.setText("Input Equation Of Graph :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Input Equation Of Graph :");

        MainOutput.setEditable(false);
        MainOutput.setColumns(20);
        MainOutput.setRows(5);
        jScrollPane1.setViewportView(MainOutput);

        Titlenumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Titlenumber.setText("Input Recurring Number:");

        recbutton.setText("Generate Question");
        recbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recbuttonActionPerformed(evt);
            }
        });

        derbutton.setText("Generate Question");
        derbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derbuttonActionPerformed(evt);
            }
        });

        tanbutton.setText("Generate Question");
        tanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanbuttonActionPerformed(evt);
            }
        });

        secbutton.setText("Generate Question");
        secbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secbuttonActionPerformed(evt);
            }
        });

        helpbutton.setText("User Guide");
        helpbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(derbutton)
                .addGap(67, 67, 67)
                .addComponent(secbutton)
                .addGap(113, 113, 113)
                .addComponent(tanbutton)
                .addGap(120, 120, 120)
                .addComponent(recbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(Title))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(Derivative)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Title1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(1, 1, 1)
                                        .addComponent(InputX1Secant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(InputX2Secant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(77, 77, 77))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(SlopeOfSecant, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SlopeOfTangent)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(Title4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(InputXTangent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(InputYTangent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(findxtangent)
                                        .addGap(29, 29, 29)
                                        .addComponent(findytangent)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(RecurringNumbers))
                                    .addComponent(InputRecurring, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Titlenumber)
                                .addGap(27, 27, 27))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(InputEquationTangent, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helpbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InputEquationSecant, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(InputEquationDerivative, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Title2)))
                        .addGap(68, 68, 68)
                        .addComponent(Title5)))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(helpbutton)
                        .addGap(18, 18, 18)
                        .addComponent(ExitButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Title)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RecurringNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Titlenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InputRecurring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Derivative)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SlopeOfTangent)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(findxtangent)
                                    .addComponent(findytangent))
                                .addGap(7, 7, 7)
                                .addComponent(Title4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SlopeOfSecant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Title1)
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputX1Secant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InputX2Secant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Title2)
                                        .addComponent(InputEquationDerivative, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(InputYTangent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(InputXTangent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputEquationSecant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Title5))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(derbutton)
                                    .addComponent(secbutton)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(InputEquationTangent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tanbutton)
                                    .addComponent(recbutton))))
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DerivativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DerivativeActionPerformed
        // TODO add your handling code here:
        SlopeOfSecant.setEnabled(false);
        RecurringNumbers.setEnabled(false);
        SlopeOfTangent.setEnabled(false);
        derbutton.setEnabled(true);
        Derivative.setEnabled(false);
        
    }//GEN-LAST:event_DerivativeActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        //exit button
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void SlopeOfSecantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlopeOfSecantActionPerformed
        // TODO add your handling code here:
        Derivative.setEnabled(false);
        RecurringNumbers.setEnabled(false);
        SlopeOfTangent.setEnabled(false);
        secbutton.setEnabled(true);
        SlopeOfSecant.setEnabled(false);
    }//GEN-LAST:event_SlopeOfSecantActionPerformed

    private void RecurringNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecurringNumbersActionPerformed
        // TODO add your handling code here:
        Derivative.setEnabled(false);
        SlopeOfSecant.setEnabled(false);
        SlopeOfTangent.setEnabled(false);
        recbutton.setEnabled(true);
        RecurringNumbers.setEnabled(false);
    }//GEN-LAST:event_RecurringNumbersActionPerformed

    private void SlopeOfTangentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlopeOfTangentActionPerformed
        // TODO add your handling code here:
        Derivative.setEnabled(false);
        SlopeOfSecant.setEnabled(false);
        RecurringNumbers.setEnabled(false);
        tanbutton.setEnabled(true);
        findxtangent.setEnabled(true);
        findytangent.setEnabled(true);
        SlopeOfTangent.setEnabled(false);
    }//GEN-LAST:event_SlopeOfTangentActionPerformed

    private void findxtangentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findxtangentActionPerformed
        // TODO add your handling code here:
        findytangent.setEnabled(false);
        InputXTangent.setEditable(false);
    }//GEN-LAST:event_findxtangentActionPerformed

    private void findytangentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findytangentActionPerformed
        // TODO add your handling code here:
        findxtangent.setEnabled(false);
        InputYTangent.setEditable(false);
    }//GEN-LAST:event_findytangentActionPerformed

    private void Clear () {
        // This custom function clears all the inputs
        InputEquationDerivative.setText("");
        InputYTangent.setText("");
        InputXTangent.setText("");
        InputEquationTangent.setText("");
        InputX1Secant.setText("");
        InputX2Secant.setText("");
        InputEquationSecant.setText("");
        InputRecurring.setText("");
    }
    
    private void Reset () {
        findxtangent.setEnabled(false);
        findytangent.setEnabled(false);
        derbutton.setEnabled(false);
        secbutton.setEnabled(false);
        recbutton.setEnabled(false);
        tanbutton.setEnabled(false);
        Derivative.setEnabled(true);
        SlopeOfSecant.setEnabled(true);
        SlopeOfTangent.setEnabled(true);
        RecurringNumbers.setEnabled(true);
    }
    
    public static String FormatRecurring(String Rec){
        Rec=Rec.replaceAll("_", "\u0305");
        return Rec;
    }
    
    public static String Superscript(String Equation){
            // "\\" is used before "^" to signify it is NOT a special command.
            Equation = Equation.replaceAll("\\^0", "⁰");
            Equation = Equation.replaceAll("\\^1", "¹");
            Equation = Equation.replaceAll("\\^2", "²");
            Equation = Equation.replaceAll("\\^3", "³");
            Equation = Equation.replaceAll("\\^4", "⁴");
            Equation = Equation.replaceAll("\\^5", "⁵");
            Equation = Equation.replaceAll("\\^6", "⁶");
            Equation = Equation.replaceAll("\\^7", "⁷");
            Equation = Equation.replaceAll("\\^8", "⁸");
            Equation = Equation.replaceAll("\\^9", "⁹");
            
        return Equation;
    
    }
    
    private void derbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derbuttonActionPerformed
        // This code gets user input and prints it to screen in question format
        Qs[0][0] = "Consider the function:";
        Qs[0][1] = "use first principles to determine the derivative of this function.";
        Qs[1][0] = "Given the following equation of the graph";
        Qs[1][1] = "find the derivative.";
        Qs[2][0] = "Use the following equation provided:";
        Qs[2][1] = "calculate the derivative.";
        Qs[3][0] = "Use the function provided";
        Qs[3][1] = "work out the derivative.";
        Qs[4][0] = "Using the equation:";
        Qs[4][1] = "find the derivative form.";
        Qs[5][0] = "The equation of a curve is:";
        Qs[5][1] = "find the derivative form of the equation.";
        
        
        Equation = InputEquationDerivative.getText();
        String Output = "";
        int RandNum1 = (int) Math.floor(Math.random()*(5));
        int RandNum2 = (int) Math.floor(Math.random()*(5));
        Output += Qs[RandNum1][0] + " " + Superscript(Equation) + ", " + Qs[RandNum2][1];
        MainOutput.setText(Output);     
        Clear();
        Reset();
    }//GEN-LAST:event_derbuttonActionPerformed

    private void tanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanbuttonActionPerformed
        //  This code gets user input and prints it to screen in question format
        String Given = "";
        String Variable = "";
        if (findxtangent.isEnabled()== true){
            Given = InputYTangent.getText();
            Variable = "y";
        }
        
        if (findytangent.isEnabled()== true){
            Given = InputXTangent.getText();
            Variable = "x";
        }
        Equation = InputEquationTangent.getText();
        
        Qs[0][0] = "Given the function:";
        Qs[0][1] = "find the equation of the tangent line.";
        Qs[1][0] = "Consider the following equation of the graph:";
        Qs[1][1] = "calculate the equation of the tangent";
        Qs[2][0] = "Use the following equation provided:";
        Qs[2][1] = "solve for the equation of the tangent.";
        Qs[3][0] = "The equation of a curve is:";
        Qs[3][1] = "find the equation of the tangent line.";
        Qs[4][0] = "Using the equation:";
        Qs[4][1] = "use first principles to determine the equation of the tangent line.";
        Qs[5][0] = "Using the following equation:";
        Qs[5][1] = "determine the equation of its tangent.";
        
      
        String Output = "";
        int RandNum1 = (int) Math.floor(Math.random()*(5));
        int RandNum2 = (int) Math.floor(Math.random()*(5));
        Output += Qs[RandNum1][0] + " " + Superscript(Equation) + ", " 
                + Qs[RandNum2][1] + " that goes through the point where " + Variable + " = " + Given + ".";
        
        MainOutput.setText(Output);
        Clear();
        Reset();
        InputXTangent.setEditable(true);
        InputYTangent.setEditable(true);
        
    }//GEN-LAST:event_tanbuttonActionPerformed

    private void secbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secbuttonActionPerformed
        // This code gets user input and prints it to screen in question format
        String X1 = InputX1Secant.getText();
        String X2 = InputX2Secant.getText();
        Equation = InputEquationSecant.getText();
        
        Qs[0][0] = "Given the function:";
        Qs[0][1] = "find the average slope of the curve.";
        Qs[1][0] = "Consider the following equation of the graph:";
        Qs[1][1] = "calculate the slope of the secant.";
        Qs[2][0] = "Use the following equation provided:";
        Qs[2][1] = "find the slope of the secant.";
        Qs[3][0] = "The equation of a curve is:";
        Qs[3][1] = "use first principles to determine the slope of the secant.";
        Qs[4][0] = "Using the equation:";
        Qs[4][1] = "work out the slope of the secant.";
        Qs[5][0] = "Using the following equation:";
        Qs[5][1] = "determine the slope of the secant.";
        
        
        String Output = "";
        int RandNum1 = (int) Math.floor(Math.random()*(5));
        int RandNum2 = (int) Math.floor(Math.random()*(5));
        Output += Qs[RandNum1][0] + " " + Superscript(Equation) + ", " 
                + Qs[RandNum2][1] + " between X₁= " + X1 + " and X₂= " + X2 + ".";
        
        MainOutput.setText(Output);
        Clear();
        Reset();
        
    }//GEN-LAST:event_secbuttonActionPerformed
    
    private void recbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recbuttonActionPerformed
        // This code gets user input and prints it to screen in question format
        Rec = InputRecurring.getText();
        
        Qs[0][0] = "Given the following recurring number:";
        Qs[0][1] = "determine the answer as a fraction and in reduced form.";
        Qs[1][0] = "Consider the recurring number:";
        Qs[1][1] = "calculate the reduced improper function of the recurring part only.";
        Qs[2][0] = "Consider the number:";
        Qs[2][1] = "express the recurring number as a fraction.";
        Qs[3][0] = "Use the recurring decimal part of the number:";
        Qs[3][1] = "express the number as a quotient of integers.";
        
        String Output = "";
        int RandNum1 = (int) Math.floor(Math.random()*(3));
        int RandNum2 = (int) Math.floor(Math.random()*(3));
        Output += Qs[RandNum1][0] + " " + FormatRecurring(Rec) + ", " + Qs[RandNum2][1];
        MainOutput.setText(Output);
        Clear();
        Reset();
    }//GEN-LAST:event_recbuttonActionPerformed

    private void helpbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpbuttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, " This program generates questions on 4 main functions of Unit 7 :Intro to Calculus."
                + "\n To output a recurring number, please press Shift + - button before the number that is going to be recurring."
                + "\n For example: 1._5_5_5 will have the 5 recurring the amount of times the 5 is after the _ symbol."
                + "\n To use a superscript(exponent), make sure to use this ^ button before the exponent number."
                + "\n For example: x^4 will output as x⁴");
    }//GEN-LAST:event_helpbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordProblemGeneratorISU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordProblemGeneratorISU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordProblemGeneratorISU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordProblemGeneratorISU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordProblemGeneratorISU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Derivative;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField InputEquationDerivative;
    private javax.swing.JTextField InputEquationSecant;
    private javax.swing.JTextField InputEquationTangent;
    private javax.swing.JTextField InputRecurring;
    private javax.swing.JTextField InputX1Secant;
    private javax.swing.JTextField InputX2Secant;
    private javax.swing.JTextField InputXTangent;
    private javax.swing.JTextField InputYTangent;
    private javax.swing.JTextArea MainOutput;
    private javax.swing.JButton RecurringNumbers;
    private javax.swing.JButton SlopeOfSecant;
    private javax.swing.JButton SlopeOfTangent;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title4;
    private javax.swing.JLabel Title5;
    private javax.swing.JLabel Titlenumber;
    private javax.swing.JButton derbutton;
    private javax.swing.JButton findxtangent;
    private javax.swing.JButton findytangent;
    private javax.swing.JButton helpbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton recbutton;
    private javax.swing.JButton secbutton;
    private javax.swing.JButton tanbutton;
    // End of variables declaration//GEN-END:variables
}
